package Principal;

import Opciones_Admin.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author daalb
 */
public class AdminWindow extends javax.swing.JFrame {

    MyIcon icon = new MyIcon();

    public AdminWindow() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/icons8_User_Shield_96px.png")).getImage());
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Titulo1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mode_valo = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        emp_nuevoyear = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(233, 247, 247));
        jPanel1.setForeground(new java.awt.Color(108, 110, 88));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(164, 207, 190));
        jPanel3.setPreferredSize(new java.awt.Dimension(520, 312));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(108, 110, 88));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        Titulo1.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 36)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(108, 110, 88));
        Titulo1.setText("ADMINISTRADOR");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_User_Shield_96px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(541, 541, 541)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(Titulo1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel12)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 150));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(108, 110, 88));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("OPCIONES DE ADMINISTRADOR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 280, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(108, 110, 88));
        jLabel5.setText("Valorizaciones por intervalo de meses");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 250, 30));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(108, 110, 88));
        jLabel6.setText("Ver movimientos de bodega del año");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 230, 30));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(108, 110, 88));
        jLabel7.setText("Ver movimientos de ventas del año");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 230, 30));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(108, 110, 88));
        jLabel9.setText("Valorizaciones de años anteriores");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 220, 30));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(108, 110, 88));
        jLabel11.setText("Valorizaciones por mes");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 170, 30));

        mode_valo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mode_valoMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(108, 110, 88));
        jLabel10.setText("Seleccione modo de valoraciòn");

        javax.swing.GroupLayout mode_valoLayout = new javax.swing.GroupLayout(mode_valo);
        mode_valo.setLayout(mode_valoLayout);
        mode_valoLayout.setHorizontalGroup(
            mode_valoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mode_valoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        mode_valoLayout.setVerticalGroup(
            mode_valoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mode_valoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(mode_valo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 230, 30));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(108, 110, 88));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Reiniciar sistema");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Warning_Shield_30px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 180, 60));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 230, 30));

        emp_nuevoyear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                emp_nuevoyearMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(108, 110, 88));
        jLabel8.setText("Empezar nuevo año");

        javax.swing.GroupLayout emp_nuevoyearLayout = new javax.swing.GroupLayout(emp_nuevoyear);
        emp_nuevoyear.setLayout(emp_nuevoyearLayout);
        emp_nuevoyearLayout.setHorizontalGroup(
            emp_nuevoyearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emp_nuevoyearLayout.createSequentialGroup()
                .addComponent(jLabel8)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        emp_nuevoyearLayout.setVerticalGroup(
            emp_nuevoyearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, emp_nuevoyearLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(emp_nuevoyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 140, 30));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 230, 30));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 150, 30));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, 240, 30));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 230, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked
    int xx, xy;
    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_jPanel3MouseDragged

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void mode_valoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mode_valoMousePressed
        Modo_Valorizacion mv = new Modo_Valorizacion();
        this.dispose();
        mv.setVisible(true);
    }//GEN-LAST:event_mode_valoMousePressed

    public boolean existe(File folder) {
        if (folder.exists()) {
            return true;
        } else {
            return false;
        }

    }

    public void registrar_year(File registro_year, String year) throws IOException {
        FileWriter fw = null;
        PrintWriter pw = null;
        fw = new FileWriter(registro_year, true);
        pw = new PrintWriter(fw);
        pw.println(year);
        pw.close();
        agg_listayear(registro_year);
    }

    public void registar_intervalo(File registro_intervalos, int intervalo) throws IOException {
        FileWriter fw = null;
        PrintWriter pw = null;
        fw = new FileWriter(registro_intervalos, true);
        pw = new PrintWriter(fw);
        if (intervalo == 0) {
            for (int i = 0; i < 6; i++) {
                pw.println(i + 1);
            }
        } else if (intervalo == 1) {
            for (int i = 0; i < 4; i++) {
                pw.println(i + 1);
            }
        } else if (intervalo == 2) {
            for (int i = 0; i < 2; i++) {
                pw.println(i + 1);
            }
        }
        pw.close();
        agg_listinterval(registro_intervalos);
    }

    Year ptry = null;

    public void agg_listayear(File registro_year) throws FileNotFoundException, IOException {
        Year p = ptry;
        FileReader fr = null;
        BufferedReader br = null;
        fr = new FileReader(registro_year);
        br = new BufferedReader(fr);
        String linea;
        while ((linea = br.readLine()) != null) {
            if (ptry == null) {
                ptry = new Year(linea, null, null);
                p = ptry;
                System.out.println("Esta es la info de la principal " + p.getInfo());
            } else {
                Year q = new Year(linea, null, null);
                p.setLinkyea(q);
                System.out.println("Esta es la info de la principal " + p.getInfo());
                p = q;
            }
            p = ptry;
        }
        br.close();
        fr.close();
    }

    public void agg_listinterval(File registro_intervalos) throws FileNotFoundException, IOException {
        Year yy = ptry;
        FileReader fr = null;
        BufferedReader br = null;
        fr = new FileReader(registro_intervalos);
        br = new BufferedReader(fr);
        String linea, lineaaux = "";
        while ((linea = br.readLine()) != null) {
            lineaaux = linea;
            if (yy != null) {
                Interval intv = new Interval(lineaaux, null, null);
                if (yy.getLinkin() == null) {
                    yy.setLinkin(intv);
                } else {
                    Interval intv2 = yy.getLinkin();
                    while (intv2.getIn() != null) {
                        intv2 = intv2.getIn();
                    }
                    intv2.setIn(intv);
                }
            }
        }
        br.close();
        fr.close();
        showlist();
    }

    public void showlist() {
        System.out.println("ShowList");
        if (ptry != null) {
            Year p = ptry;
            while (p != null) {
                System.out.println(p.getInfo());
                if (p.getLinkin() != null) {
                    Interval z = p.getLinkin();
                    while (z != null) {
                        System.out.println("-->" + z.getInfo());
                        z = z.getIn();
                    }
                }
                p = p.getLinkyea();
            }
        } else {
            System.out.println("No hay lista que mostrar");
        }
    }

    public void agg_intervalos(String year, int intervalo) {
        if (intervalo == 0) {
            for (int i = 0; i < 6; i++) {
                File folder = new File("C:\\Users\\daalb\\Documents\\NetBeansProjects\\E&D\\Años" + "\\" + year + "\\" + Integer.toString(i + 1));
                folder.mkdirs();
                agg_meses(intervalo, folder, year);
            }
        } else if (intervalo == 1) {
            for (int i = 0; i < 4; i++) {
                File folder = new File("C:\\Users\\daalb\\Documents\\NetBeansProjects\\E&D\\Años" + "\\" + year + "\\" + Integer.toString(i + 1));
                folder.mkdirs();
                agg_meses(intervalo, folder, year);

            }
        } else if (intervalo == 2) {
            for (int i = 0; i < 2; i++) {
                File folder = new File("C:\\Users\\daalb\\Documents\\NetBeansProjects\\E&D\\Años" + "\\" + year + "\\" + Integer.toString(i + 1));
                folder.mkdirs();
                agg_meses(intervalo, folder, year);
            }
        }
    }

    public void agg_meses(int intervalo, File file, String year) {
        if (intervalo == 0) {
            for (int j = 0; j < 6; j++) {
                for (int i = 0; i < 2; i++) {
                    try {
                        File mes = new File("C:\\Users\\daalb\\Documents\\NetBeansProjects\\E&D\\Años" + "\\" + year
                                + "\\" + Integer.toString(j + 1) + "\\Mes " + Integer.toString(i + 1) + " .txt ");
                        if (mes.createNewFile()) {
                            System.out.println("Se creo el archivo");
                        }
                    } catch (Throwable e) {
                        System.out.println("No se pudo crear");
                    };
                }
            }
        } else if (intervalo == 1) {
            for (int j = 0; j < 4; j++) {
                for (int i = 0; i < 3; i++) {
                    try {
                        File mes = new File("C:\\Users\\daalb\\Documents\\NetBeansProjects\\E&D\\Años" + "\\" + year
                                + "\\" + Integer.toString(j + 1) + "\\Mes " + Integer.toString(i + 1) + " .txt ");
                        if (mes.createNewFile()) {
                            System.out.println("Se creo el archivo");
                        }
                    } catch (Throwable e) {
                        System.out.println("No se pudo crear");
                    };
                }
            }
        } else if (intervalo == 2) {
            for (int j = 0; j < 2; j++) {
                for (int i = 0; i < 6; i++) {
                    try {
                        File mes = new File("C:\\Users\\daalb\\Documents\\NetBeansProjects\\E&D\\Años" + "\\" + year
                                + "\\" + Integer.toString(j + 1) + "\\Mes " + Integer.toString(i + 1) + " .txt ");
                        if (mes.createNewFile()) {
                            System.out.println("Se creo el archivo");
                        }
                    } catch (Throwable e) {
                        System.out.println("No se pudo crear");
                    };
                }
            }
        }

    }

    private void emp_nuevoyearMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emp_nuevoyearMousePressed
        String year = JOptionPane.showInputDialog(null, "Ingrese el año", "Año", JOptionPane.INFORMATION_MESSAGE);
        String[] op = {"Bimestral", "Trimestral", "Semestral"};
        int intervalo = JOptionPane.showOptionDialog(null, "Escoja el intervalo de tiempo", "Intervalo", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, icon, op, op[0]);
        File folder = new File("C:\\Users\\daalb\\Documents\\NetBeansProjects\\E&D\\Años" + "\\" + year);
        if (existe(folder) == true) {
            JOptionPane.showMessageDialog(null, "Ya existe este año", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            folder.mkdirs();
            File registro_years = new File("C:\\Users\\daalb\\Documents\\NetBeansProjects\\E&D\\Años\\Años.txt");
            File registro_intervalos = new File("C:\\Users\\daalb\\Documents\\NetBeansProjects\\E&D\\Años\\" + year + "\\Intervalos.txt");
            try {
                registrar_year(registro_years, year);
                registar_intervalo(registro_intervalos, intervalo);
                agg_intervalos(year, intervalo);
            } catch (IOException ex) {
                Logger.getLogger(AdminWindow.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_emp_nuevoyearMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo1;
    private javax.swing.JPanel emp_nuevoyear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel mode_valo;
    // End of variables declaration//GEN-END:variables
}
