
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Erick Solano
 */
public class Nuevo_Producto extends javax.swing.JFrame {

    /**
     * Creates new form Nuevo_Producto
     */
    public Nuevo_Producto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        Crear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Cantidad");

        jLabel3.setText("Precio Unitario");

        Crear.setText("Añadir");
        Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Crear)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nombre)
                        .addComponent(cantidad)
                        .addComponent(precio, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Crear)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed
    Nodo_Productos ptr = null, p, ult = null;
    public void Actualizar() {
        ptr = null;
        String Nombre = "", Precio = "", Cantidad = "", Random = "";
        File archivo;
        FileReader fr = null;
        BufferedReader br;
        try {
            archivo = new File("archivo_productos.txt");
            fr = new FileReader(archivo);
            br = new BufferedReader(fr);
            String linea;
            while ((linea = br.readLine()) != null) {
                int punt = 0;
                int cont = 0;
                for (int i = 0; i < linea.length(); i++) {
                    if (linea.substring(i, i + 1).equals(";")) {
                        if (punt == 0) {
                            Nombre = linea.substring(cont, i);
                        }
                        if (punt == 1) {
                            Cantidad = linea.substring(cont, i);
                        }
                        if (punt == 2) {
                            Precio = linea.substring(cont, i);
                        }
                        if (punt == 3) {
                            Random = linea.substring(cont, i);
                        }
                        punt++;
                        cont = i + 1;
                    }
                }
                if (ptr == null) {
                    ptr = new Nodo_Productos(Nombre, Integer.parseInt(Cantidad), Float.parseFloat(Precio), Integer.parseInt(Random), null, null);
                    ptr.setLlink(null);
                    p = ptr;
                } else {
                    Nodo_Productos q = new Nodo_Productos(Nombre, Integer.parseInt(Cantidad), Float.parseFloat(Precio), Integer.parseInt(Random), null, null);
                    p.setRlink(q);
                    q.setLlink(p);
                    p = q;
                }
                p.setRlink(null);
                ult = p;
            }
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (null != fr) {
                    fr.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }
    }

    public void Mostrar() {
        Nodo_Productos p = ptr;
        while (p != null) {
            System.out.println(p.getNombre());
            p = p.getRlink();
        }
    }

    public void Registrar(int N) {

        if (Pattern.compile("[A-Za-z ]*").matcher(nombre.getText()).matches() && !nombre.getText().equals("") && !Pattern.compile("[ \\t\\n\\x0b\\r\\f]*").matcher(nombre.getText()).matches()) {
            try {
                int cant = Integer.parseInt(cantidad.getText());
                if (cant > 0) {
                    try {
                        float pre = Float.parseFloat(precio.getText());
                        if (pre >= 0) {
                            Crear_Producto(N);
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "¡ERROR! Ingrese un precio valido", "Atencion", JOptionPane.ERROR_MESSAGE);
                    }
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "¡ERROR! Ingrese una cantidad valida", "Atencion", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "NOMBRE NO VALIDO", "ATENCIÓN", JOptionPane.ERROR_MESSAGE);

        }

    }

    public void Crear_Producto(int N) {

        String ruta = "archivo_productos.txt";
        File archivo_productos = new File(ruta);
        BufferedWriter BFW;
        if (archivo_productos.exists()) {
            try {
                BFW = new BufferedWriter(new FileWriter(archivo_productos, true));
            } catch (IOException ex) {
                Logger.getLogger(Nuevo_Producto.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                BFW = new BufferedWriter(new FileWriter(archivo_productos, true));
            } catch (IOException ex) {
                Logger.getLogger(Nuevo_Producto.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        FileWriter archivo = null;
        PrintWriter PW = null;
        try {
            archivo = new FileWriter("archivo_productos.txt", true);
            PW = new PrintWriter(archivo);
            int R = (int) (Math.random() * 1000) + 1;

            Nodo_Productos p = ptr;
            while (p != null && N == 2) {
                if (p.getRamdom() == R) {
                    R = (int) (Math.random() * 1000) + 1;
                    p = ptr;
                } else {
                    p = p.getRlink();
                }
            }
            PW.println(nombre.getText() + ";" + cantidad.getText() + ";" + precio.getText() + ";" + R + ";");
            nombre.setText("");
            cantidad.setText("");
            precio.setText("");
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (null != archivo) {
                    archivo.close();
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
        }

    }
    private void CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearActionPerformed
        // TODO add your handling code here:
        String ruta = "archivo_productos.txt";
        int N = 1;
        File archivo_productos = new File(ruta);
        if (archivo_productos.exists()) {
            Actualizar();
            N = 2;
        }
        Registrar(N);
        Actualizar();
        Mostrar();
    }//GEN-LAST:event_CrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nuevo_Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nuevo_Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Crear;
    private javax.swing.JTextField cantidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField precio;
    // End of variables declaration//GEN-END:variables

}
